openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /contratos-generales/{id}:
    get:
      operationId: ContratoGeneralController_consultarInfoContrato
      parameters:
        - name: id
          required: true
          in: path
          description: ID del contrato general
          schema:
            type: number
      responses:
        '200':
          description: Retorna detalle de un contrato-general.
        '400':
          description: Error en la solicitud.
      summary: Retorna información de contrato-general por ID.
      tags: &ref_0
        - ContratoGeneral
  /contratos-generales:
    get:
      operationId: ContratoGeneralController_consultarContratos
      parameters:
        - name: sortBy
          required: false
          in: query
          description: Campo por el cual ordenar
          schema:
            type: string
        - name: orderBy
          required: false
          in: query
          description: Dirección del ordenamiento
          schema:
            enum:
              - ASC
              - DESC
            type: string
        - name: limit
          required: false
          in: query
          description: Número de registros a retornar
          schema:
            minimum: 0
            type: number
        - name: offset
          required: false
          in: query
          description: Número de registros a saltar
          schema:
            minimum: 0
            type: number
        - name: queryFilter
          required: false
          in: query
          description: Filtros aplicados para el crud
          schema:
            type: string
      responses:
        '200':
          description: Lista de contratos generales
      summary: Retorna información de contratos generales con filtros y paginación
      tags: *ref_0
  /espacios-fisicos/sedes:
    get:
      description: Obtiene todas las sedes activas del sistema
      operationId: EspaciosFisicosController_obtenerSedes
      parameters: []
      responses:
        '200':
          description: Lista de sedes obtenida exitosamente
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      Success:
                        type: boolean
                        example: true
                      Status:
                        type: number
                        example: 200
                      Message:
                        type: string
                        example: Sedes obtenidas exitosamente
                      Data:
                        type: array
                        items:
                          properties:
                            Id:
                              type: number
                              example: 1
                            Nombre:
                              type: string
                              example: Sede Principal
        '404':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  Success:
                    type: boolean
                    example: false
                  Status:
                    type: number
                    example: 404
                  Message:
                    type: string
                    example: No se encontraron sedes activas
      summary: Obtener sedes
      tags: &ref_1
        - Espacios Físicos
  /espacios-fisicos/dependencias-sede/{id}:
    get:
      description: Obtiene todas las dependencias asociadas a una sede específica
      operationId: EspaciosFisicosController_obtenerDependencias
      parameters:
        - name: id
          required: true
          in: path
          description: Identificador de la sede
          schema:
            type: string
      responses:
        '200':
          description: Lista de dependencias obtenida exitosamente
          content:
            application/json:
              schema:
                allOf:
                  - properties:
                      Success:
                        type: boolean
                        example: true
                      Status:
                        type: number
                        example: 200
                      Message:
                        type: string
                        example: Dependencias obtenidas exitosamente
                      Data:
                        type: array
                        items:
                          properties:
                            id:
                              type: number
                              example: 1
                            nombre:
                              type: string
                              example: Facultad de Ingeniería
        '404':
          description: ''
          content:
            application/json:
              schema:
                properties:
                  Success:
                    type: boolean
                    example: false
                  Status:
                    type: number
                    example: 404
                  Message:
                    type: string
                    example: No se encontraron dependencias
      summary: Obtener dependencias por sede
      tags: *ref_1
info:
  title: Gestion Contractual API MID
  description: API
  version: 1.0.0
  contact: {}
tags:
  - name: API
    description: ''
servers: []
components:
  schemas: {}
